import React from "react";
import BuyersGridCard from "./BuyersGridCard";
const buyersInfo = [
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
  {
    BuyerName: "Jacob Jason",
    img: "/Assets/Dashboard/User.jpg",
    PurchasedProducts: "23",
    Address: "st Paul Street Los Vegas",
    AmountSpent: "$453",
    email: "JhonMckay@gmail.com",
    phoneNumber: "+923409574",
    JoiningDate: "24-03-2021",
    style: "",
  },
];
interface Props {
  style: string;
}
const BuyersGridView: React.FC<Props> = ({ style }) => {
  return (
    <div
      className={`w-full h-full grid md:grid-cols-2 lg:grid-cols-3 gap-6 ${style}`}>
      {buyersInfo.map((item, index) => {
        return (
          <BuyersGridCard
            key={index}
            img={item.img}
            BuyerName={item.BuyerName}
            PurchasedProducts={item.PurchasedProducts}
            Address={item.Address}
            AmountSpent={item.AmountSpent}
            email={item.email}
            phoneNumber={item.phoneNumber}
            JoiningDate={item.JoiningDate}
          />
        );
      })}
    </div>
  );
};

export default BuyersGridView;
