import { MdElectricalServices } from "react-icons/md";
import { FaGamepad } from "react-icons/fa";
import { FaMobileAlt } from "react-icons/fa";
import { AiFillHome } from "react-icons/ai";
import { MdToys } from "react-icons/md";
import { RiMotorbikeFill } from "react-icons/ri";
import { ImMan } from "react-icons/im";
import { ImWoman } from "react-icons/im";
import { RxDesktop } from "react-icons/rx";
import { MdOutlineSettingsSuggest } from "react-icons/md";
import { FaFacebookF } from "react-icons/fa";
import { FaTwitter } from "react-icons/fa";
import { FaLinkedinIn } from "react-icons/fa";

export const Data = {
  logo: {
    dark: "",
    white: "/Assets/logo.svg",
  },
  ContactHeader: {
    NavItem: [
      {
        Name: "Customer Support",
        Route: "/faq",
      },
    ],
    ContactInFo: {
      Phone: "+923116042176",
      Email: "business@gmail.com",
    },
  },
  SearchHeader: {
    SearchCategory: [
      {
        Title: "Electronics",
        Value: "Electronics",
      },
      {
        Title: "Game",
        Value: "Game",
      },
      {
        Title: "Mobile",
        Value: "Mobile",
      },
      {
        Title: "Lifestyle",
        Value: "Lifestyle",
      },
      {
        Title: "Men's Fashion",
        Value: "Men's Fashio",
      },
      {
        Title: "Television",
        Value: "Television",
      },
    ],
  },
  Features: {
    Items: [
      {
        Title: "Electronics",
        Route: "",
        Image: "/categories/electronics.webp",
      },
      {
        Title: "Game",
        Route: "",
        Image: "/categories/game.webp",
      },
      {
        Title: "Lifestyle",
        Route: "",
        Image: "/categories/lifestyle.webp",
      },
      {
        Title: "Babies & Toys",
        Route: "",
        Image: "/categories/babies-toys.webp",
      },
      {
        Title: "Bike",
        Route: "",
        Image: "/categories/bike.webp",
      },
      {
        Title: "Mobile",
        Route: "",
        Image: "/categories/mobile.webp",
      },
      {
        Title: "Mens Fashion",
        Route: "",
        Image: "/categories/mens-fasion.webp",
      },
      {
        Title: "Woman Fashion",
        Route: "",
        Image: "/categories/womans-fasion.webp",
      },
    ],
  },
  BestSeller: {
    topSection: [
      {
        image: "/Assets/Home/BestSeller/shopnoBd.png",
        title: "Shopno BD",
      },
      {
        image: "/Assets/Home/BestSeller/2.webp",
        title: "Eecoms Shop",
      },
      {
        image: "/Assets/Home/BestSeller/3.webp",
        title: "Fusion X",
      },
      {
        image: "/Assets/Home/BestSeller/4.webp",
        title: "Rikayi Rox",
      },
      {
        image: "/Assets/Home/BestSeller/5.png",
        title: "Habbriyi",
      },
      {
        image: "/Assets/Home/BestSeller/6.webp",
        title: "Rayhans",
      },
    ],
  },
  Navbar: {
    Shop: {
      Title: "Shop",
      Category1: {
        Title: "ELECTRONICS",
        Items: [
          {
            Name: "Mobiles",
            Route: "",
          },
          {
            Name: "Monitor",
            Route: "",
          },
          {
            Name: "camera",
            Route: "",
          },
        ],
      },
      Category2: {
        Title: "GAME",
        Items: [
          {
            Name: "Controller",
            Route: "",
          },
          {
            Name: "PlayStation",
            Route: "",
          },
          {
            Name: "Need For Speed",
            Route: "",
          },
        ],
      },
      Category3: {
        Title: "ACCESSORIES",
        Items: [
          {
            Name: "Desktop",
            Route: "",
          },
          {
            Name: "Headphone",
            Route: "",
          },
          {
            Name: "Mouse",
            Route: "",
          },
        ],
      },
    },
    AllCategories: [
      {
        Name: "Electronics",
        Route: "",
        Icon: <MdElectricalServices size={16} color="#1D1D1D" />,
      },
      {
        Name: "Game",
        Route: "",
        Icon: <FaGamepad size={16} color="#1D1D1D" />,
      },
      {
        Name: "Mobile",
        Route: "",
        Icon: <FaMobileAlt size={16} color="#1D1D1D" />,
      },
      {
        Name: "Lifestyle",
        Route: "",
        Icon: <AiFillHome size={16} color="#1D1D1D" />,
      },
      {
        Name: "Toys",
        Route: "",
        Icon: <MdToys size={16} color="#1D1D1D" />,
      },
      {
        Name: "Bike",
        Route: "",
        Icon: <RiMotorbikeFill size={16} color="#1D1D1D" />,
      },
      {
        Name: "Men's Fashion",
        Route: "",
        Icon: <ImMan size={16} color="#1D1D1D" />,
      },
      {
        Name: "Woman's Fashion",
        Route: "",
        Icon: <ImWoman size={16} color="#1D1D1D" />,
      },
      {
        Name: "Television",
        Route: "",
        Icon: <RxDesktop size={16} color="#1D1D1D" />,
      },
      {
        Name: "Accessories",
        Route: "",
        Icon: <MdOutlineSettingsSuggest size={16} color="#1D1D1D" />,
      },
    ],
    Menu: [
      {
        Name: "Sellers",
        Route: "",
      },
      {
        Name: "Blogs",
        Route: "",
      },
      {
        Name: "About",
        Route: "",
      },
      {
        Name: "Contact",
        Route: "",
      },
    ],
    SingleNavMenu: [
      {
        Name: "Home",
        Route: "/",
      },
      {
        Name: "Electronics",
        Route: "",
      },
      {
        Name: "Game",
        Route: "",
      },
      {
        Name: "Mobile",
        Route: "",
      },
      {
        Name: "Lifestyle",
        Route: "",
      },
      {
        Name: "Toys",
        Route: "",
      },
      {
        Name: "Bike",
        Route: "",
      },
      {
        Name: "Men's Fashion",
        Route: "",
      },
      {
        Name: "Woman's Fashion",
        Route: "",
      },
      {
        Name: "Television",
        Route: "",
      },
      {
        Name: "Accessories",
        Route: "",
      },
      {
        Name: "Woman's Fashion",
        Route: "",
      },
    ],
  },
  ShopByBrand: {
    Brands: [
      {
        Image: "/shopByBrand/tesla.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/brave.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/firefox.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/huawei.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/google.png",
        Route: "",
      },
      {
        Image: "/shopByBrand/apple.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/lenovo.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/mircrosoft.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/nexus.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/oneplus.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/tencent.webp",
        Route: "",
      },
      {
        Image: "/shopByBrand/facebook.webp",
        Route: "",
      },
    ],
  },
  BestProduts: {
    Products: [
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/apple-air.webp",
        Name: "Apple Air 2022",
        CurrentPrice: "$250000",
        OfferPrice: " $150000.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        Name: "Apple watch pro",
        CurrentPrice: "$45000",
        OfferPrice: " $40000.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Name: "Appple macbook pro 2020",
        CurrentPrice: "$12000",
        OfferPrice: " $10000.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/asus-zenbook-desktop.webp",
        Name: "Asus zenbook desktop",
        CurrentPrice: "$35000",
        OfferPrice: " $33000.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/mi-laptop-pro.webp",
        Name: "Mi Laptop pro",
        CurrentPrice: "$50000",
        OfferPrice: " $45000.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/mini-sound-box.webp",
        Name: "Mini Sound Box",
        CurrentPrice: "$1235",
        OfferPrice: " $1200.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/orange-portable-speaker.webp",
        Name: "JBL Clip 4 Orange Portable Speaker",
        CurrentPrice: "$150.00",
        OfferPrice: " $133.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/realme-mini-music.webp",
        Name: "Realme mini music",
        CurrentPrice: "$800",
        OfferPrice: " $659.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/sony-camera-m1.webp",
        Name: "Sony camera m1",
        CurrentPrice: "$3000",
        OfferPrice: " $2800.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/sony-joystick-v1.webp",
        Name: "Sony joystick v1",
        CurrentPrice: "$1000",
        OfferPrice: " $900.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Apple watch pro",
        CurrentPrice: "$7000",
        OfferPrice: " $5000.00",
      },
      {
        Route: "",
        Image: "/Assets/Home/bestproducts/sony-playstone-pro.webp",
        Name: "Sony playstone pro",
        CurrentPrice: "$12000",
        OfferPrice: " $10000.00",
      },
    ],
  },
  FooterData: {
    About:
      "We know there are a lot of threa developers our but we pride into a firm in the industry.",
    Features: [
      {
        Title: "Terms Condition",
        Route: "",
      },
      {
        Title: "Best Products",
        Route: "",
      },
      {
        Title: "Best Sellers",
        Route: "",
      },
    ],
    General: [
      {
        Title: "Blog",
        Route: "",
      },
      {
        Title: "Shop",
        Route: "",
      },
      {
        Title: "Support",
        Route: "",
      },
    ],
    Helpful: [
      {
        Title: "About Us",
        Route: "",
      },
      {
        Title: "Support",
        Route: "",
      },
      {
        Title: "Contact Us",
        Route: "",
      },
    ],
    Social: [
      {
        Icon: <FaFacebookF color="#797979" size={15} />,
        Route: "",
      },
      {
        Icon: <FaTwitter color="#797979" size={17} />,
        Route: "",
      },
      {
        Icon: <FaLinkedinIn color="#797979" size={17} />,
        Route: "",
      },
    ],
  },
  AccordinData: {
    Data: [
      {
        Title: "How To Download IOS App",
        AriaControls: "panel1a-content",
        Id: "panel1a-header",
        Detail:
          " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis eget.",
      },
      {
        Title: "How To Download App",
        AriaControls: "panel2a-content",
        Id: "panel2a-header",
        Detail:
          " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis eget.",
      },
      {
        Title: "How To Download Elementor",
        AriaControls: "panel3a-content",
        Id: "panel3a-header",
        Detail:
          " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis eget.",
      },
      {
        Title: "How To Download Wordpress",
        AriaControls: "panel4a-content",
        Id: "panel4a-header",
        Detail:
          " Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendissemalesuada lacus ex, sit amet blandit leo lobortis eget.",
      },
    ],
  },
  BuyerData: {
    Favourites: [
      {
        id: 1,
        Name: "Sony Joystick Pro",
        Picture: "/Assets/Home/bestproducts/sony-joystick-v1.webp",
        Price: 20,
        Category: "Electronics",
      },
      {
        id: 2,
        Name: "Sony Joystick Pro",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Price: 20,
        Category: "Games",
      },
      {
        id: 3,
        Name: "Mi Laptop Pro",
        Picture: "/Assets/Home/bestproducts/mi-laptop-pro.webp",
        Price: 2000,
        Category: "Electronics",
      },

      {
        id: 4,
        Name: "Sony Camera",
        Picture: "/Assets/Home/bestproducts/sony-camera-m1.webp",
        Price: 30,
        Category: "Games",
      },
      {
        id: 5,
        Name: "Sony Joystick Pro",
        Picture: "/Assets/Home/bestproducts/sony-joystick-v1.webp",
        Price: 20,
        Category: "Electronics",
      },
      {
        id: 6,
        Name: "Sony Joystick Pro",
        Picture: "/Assets/Home/bestproducts/sony-joystick-v1.webp",
        Price: 20,
        Category: "Electronics",
      },
    ],
    Orders: [
      {
        id: 1,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 2,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 3,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick-v1.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 4,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 5,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 6,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick-v1.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 7,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick-v1.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 8,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 9,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 10,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 11,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 12,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
      {
        id: 13,
        Date: "04/03/2022",
        Picture: "/Assets/Home/bestproducts/sony-joystick.webp",
        Name: "Sony-JoyStick",
        Status: "Preparing",
        buttonFunction: () => {},
      },
    ],
    Cart: [
      {
        id: 1,
        Name: "Sony Joystick Pro",
        Picture: "/Assets/Home/bestproducts/sony-joystick-v1.webp",
        Quantitiy: 2,
        Category: "Electronics",
      },
      {
        id: 2,
        Name: "Sony Joystick Pro",
        Picture: "/Assets/Home/bestproducts/mini-sound-box.webp",
        Quantitiy: 4,
        Category: "Games",
      },
      {
        id: 3,
        Name: "Mi Laptop Pro",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Quantitiy: 1,
        Category: "Electronics",
      },

      {
        id: 4,
        Name: "Sony Camera",
        Picture: "/Assets/Home/bestproducts/sony-camera-m1.webp",
        Quantitiy: 3,
        Category: "Games",
      },
      {
        id: 5,
        Name: "Sony Joystick Pro",
        Picture: "/Assets/Home/bestproducts/apple-air.webp",
        Quantitiy: 2,
        Category: "Electronics",
      },
      {
        id: 6,
        Name: "Sony Joystick Pro",
        Picture: "/Assets/Home/bestproducts/sony-playstone-pro.webp",
        Quantitiy: 1,
        Category: "Electronics",
      },
    ],
  },
  SellerData: {
    cancelledOrders: [
      {
        name: "Jan",
        orders: 12,
      },
      {
        name: "Feb",
        orders: 10,
      },
      {
        name: "Mar",
        orders: 20,
      },
      {
        name: "Apr",
        orders: 22,
      },
      {
        name: "May",
        orders: 24,
      },
      {
        name: "Jun",
        orders: 29,
      },
      {
        name: "Jul",
        orders: 21,
      },
    ],
    ordersData: [
      {
        name: "Jan",
        orders: 5,
      },
      {
        name: "Feb",
        orders: 10,
      },
      {
        name: "Mar",
        orders: 20,
      },
      {
        name: "Apr",
        orders: 27,
      },
      {
        name: "May",
        orders: 18,
      },
      {
        name: "Jun",
        orders: 23,
      },
      {
        name: "Jul",
        orders: 34,
      },
    ],
    revenueData: [
      { month: "Jan", revenue: 1000 },
      { month: "Feb", revenue: 2000 },
      { month: "Mar", revenue: 3000 },
      { month: "Apr", revenue: 4000 },
      { month: "May", revenue: 5000 },
      { month: "Jun", revenue: 17000 },
      { month: "Jul", revenue: 8000 },
      { month: "Aug", revenue: 7000 },
      { month: "Sep", revenue: 6000 },
      { month: "Oct", revenue: 5000 },
      { month: "Nov", revenue: 4000 },
      { month: "Dec", revenue: 2000 },
    ],
    salesData: [
      { month: "Jan", Sales: 200 },
      { month: "Feb", Sales: 100 },
      { month: "Mar", Sales: 400 },
      { month: "Apr", Sales: 500 },
      { month: "May", Sales: 500 },
      { month: "Jun", Sales: 1700 },
      { month: "Jul", Sales: 900 },
      { month: "Aug", Sales: 700 },
      { month: "Sep", Sales: 600 },
      { month: "Oct", Sales: 500 },
      { month: "Nov", Sales: 400 },
      { month: "Dec", Sales: 200 },
    ],
    unshippedData: [
      {
        Id: 1,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 2,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 3,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 4,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 5,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 6,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 7,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 8,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 9,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 10,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        PrepTime: "2 days",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
    ],
    shippedData: [
      {
        Id: 1,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Cancelled",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 2,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Closed",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 3,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Sending",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 4,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Cancelled",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 5,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Closed",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 6,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Sending",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 7,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Cancelled",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 8,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Closed",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
      {
        Id: 9,
        Customer: "Jhon Hilly",
        Name: "Apple-Mackbook",
        Quantity: 3,
        Status: "Sending",
        PurchasedDate: "28.04.2021",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
      },
    ],
    recentSalesData: [
      {
        Id: 1,
        Name: "123esad21",
        Quantity: 3,
        PurchasedDate: "28.04.2021",
        Price: 3200,
      },
      {
        Id: 2,
        Name: "13asesad21",
        Quantity: 5,
        PurchasedDate: "28.04.2021",
        Price: 5200,
      },
      {
        Id: 3,
        Name: "",
        Quantity: 5,
        PurchasedDate: "28.04.2021",
        Price: 5200,
      },
      {
        Id: 4,
        Name: "",
        Quantity: 5,
        PurchasedDate: "28.04.2021",
        Price: 5200,
      },
      {
        Id: 5,
        Name: "",
        Quantity: 5,
        PurchasedDate: "28.04.2021",
        Price: 5200,
      },
      {
        Id: 6,
        Name: "",
        Quantity: 5,
        PurchasedDate: "28.04.2021",
        Price: 5200,
      },
      {
        Id: 7,
        Name: "",
        Quantity: 5,
        PurchasedDate: "28.04.2021",
        Price: 5200,
      },
      {
        Id: 8,
        Name: "",
        Quantity: 5,
        PurchasedDate: "28.04.2021",
        Price: 5200,
      },
    ],
    messeges: [
      {
        id: 1,
        Name: "Jhone Mckay",
        Date: "28.05.2021",
        Time: "12:33",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Messege: "  Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        id: 2,
        Name: "Jhone Mckay",
        Date: "28.05.2021",
        Time: "12:33",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Messege: "  Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        id: 3,
        Name: "Jhone Mckay",
        Date: "28.05.2021",
        Time: "12:33",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Messege: "  Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        id: 4,
        Name: "Jhone Mckay",
        Date: "28.05.2021",
        Time: "12:33",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Messege: "  Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        id: 5,
        Name: "Jhone Mckay",
        Date: "28.05.2021",
        Time: "12:33",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Messege: "  Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        id: 6,
        Name: "Jhone Mckay",
        Date: "28.05.2021",
        Time: "12:33",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Messege: "  Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
      {
        id: 7,
        Name: "Jhone Mckay",
        Date: "28.05.2021",
        Time: "12:33",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Messege: "  Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      },
    ],
    adsData: [
      {
        id: 1,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 2,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 3,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 4,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 5,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 6,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 7,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 8,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 9,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 10,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 11,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
      {
        id: 12,
        title: "Apple Watch Pro",
        date: "23-12-22",
        status: "running",
        category: "Electronics",
        condition: "Good",
        color: "red",
        price: 2300,
        negotiable: true,
        pictures: [
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
          "/Assets/Home/bestproducts/apple-watch-pro.webp",
        ],
        description:
          "Feast your eyes on vibrant details with the FHD+ Super AMOLED display, reaching 800 nits¹ for clarity even in bright daylight. Eye Comfort Shield² lowers blue light, and Real Smooth keeps the view smooth, whether you're gaming or scrolling. All on the expansive 6.5-inch Infinity-O Display. Galaxy A52 seen from the front. A scene of a man standing on a beach at sunset with pink and blue colors in the sky expands outside of the boundaries of the display. Text says Brightness 800 nits, Eye Comfort Shield, with the SGS logo and Real Smooth.",
      },
    ],
  },
  AgentData: {
    Earnings: [
      {
        id: 1,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 2,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 3,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 4,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 5,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 6,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 7,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 8,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 9,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 10,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 11,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
      {
        id: 12,
        Name: "Apple Mackbook",
        Picture: "/Assets/Home/bestproducts/apple-mackbook-pro.webp",
        Price: 800,
        Earning: 20,
        Seller: "Jhon Mckay",
        Date: "23-04-2021",
      },
    ],
    Referrals: [
      {
        id: 1,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 2,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 3,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 4,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 5,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 6,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 7,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 8,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 9,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
      {
        id: 10,
        Name: "Jhno Mckaffey",
        Picture: "/Assets/Seller/ProfilePic.jpg",
        Date: "23-04-2022",
        SellerId: 12312,
        Address: "St paul Street,Usa",
      },
    ],
    referralsData: [
      {
        name: "Jan",
        referrals: 5,
      },
      {
        name: "Feb",
        referrals: 10,
      },
      {
        name: "Mar",
        referrals: 20,
      },
      {
        name: "Apr",
        referrals: 27,
      },
      {
        name: "May",
        referrals: 18,
      },
      {
        name: "Jun",
        referrals: 23,
      },
      {
        name: "Jul",
        referrals: 34,
      },
    ],
    earningsData: [
      {
        name: "Jan",
        earning: 5,
      },
      {
        name: "Feb",
        earning: 100,
      },
      {
        name: "Mar",
        earning: 300,
      },
      {
        name: "Apr",
        earning: 270,
      },
      {
        name: "May",
        earning: 280,
      },
      {
        name: "Jun",
        earning: 230,
      },
      {
        name: "Jul",
        earning: 340,
      },
    ],
    commissionData: [
      {
        name: "Jan",
        commission: 12,
      },
      {
        name: "Feb",
        commission: 7,
      },
      {
        name: "Mar",
        commission: 20,
      },
      {
        name: "Apr",
        commission: 27,
      },
      {
        name: "May",
        commission: 18,
      },
      {
        name: "Jun",
        commission: 23,
      },
      {
        name: "Jul",
        commission: 34,
      },
    ],
  },
  ChatApp: {
    messeges: [
      {
        id: 1,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 2,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 3,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 4,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 5,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 6,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 7,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 8,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 9,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 9,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
      {
        id: 10,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },

      {
        id: 11,
        name: "Chachuu Bhaiya",
        picture: "/Assets/Seller/ProfilePic.jpg",
        lastMessege:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
        allMesseges: [
          "asdsad",
          "asdsads",
          "asdsad",
          "dsadsad",
          "sadsad",
          "asdsad",
        ],
      },
    ],
  },
  AdminData: {
    ordersData: [
      {
        name: "Jan",
        orders: 1,
      },
      {
        name: "Feb",
        orders: 2,
      },
      {
        name: "Mar",
        orders: 3,
      },
      {
        name: "Apr",
        orders: 3,
      },
      {
        name: "May",
        orders: 6,
      },
      {
        name: "Jun",
        orders: 5,
      },
      {
        name: "Jul",
        orders: 6,
      },
      {
        name: "Aug",
        orders: 7,
      },
      {
        name: "Sep",
        orders: 6,
      },
      {
        name: "Oct",
        orders: 5,
      },
      {
        name: "Sep",
        orders: 6,
      },
      {
        name: "Dec",
        orders: 7,
      },
    ],
    monthlySellers: [
      {
        month: "Jan",
        sellers: 11,
      },
      {
        month: "Feb",
        sellers: 12,
      },
      {
        month: "Mar",
        sellers: 13,
      },
      {
        month: "Apr",
        sellers: 13,
      },
      {
        month: "May",
        sellers: 16,
      },
      {
        month: "Jun",
        sellers: 15,
      },
      {
        month: "Jul",
        sellers: 16,
      },
      {
        month: "Aug",
        sellers: 17,
      },
      {
        month: "Sep",
        sellers: 16,
      },
      {
        month: "Oct",
        sellers: 15,
      },
      {
        month: "Sep",
        sellers: 16,
      },
      {
        month: "Dec",
        sellers: 17,
      },
    ],
    weeklySellers: [
      {
        week: "Week1",
        sellers: 3,
      },
      {
        week: "Week2",
        sellers: 4,
      },
      {
        week: "Week3",
        sellers: 5,
      },
      {
        week: "Week4",
        sellers: 2,
      },
    ],
    yearlySellers: [
      {
        year: "2019",
        sellers: 1400,
      },
      {
        year: "2020",
        sellers: 1100,
      },
      {
        year: "2021",
        sellers: 1300,
      },
      {
        year: "2022",
        sellers: 1100,
      },
      {
        year: "2023",
        sellers: 1600,
      },
    ],
    sellers: [
      {
        id: 1,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 2,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 3,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 4,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 5,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 6,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 7,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 8,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 9,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 10,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 11,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 12,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 13,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
      {
        id: 14,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cancelled: "5%",
        products: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        shopName: "Shopo Gadgets",
        earnings: 3400,
        orders: 12,
        joiningDate: "24-03-2021",
      },
    ],
    agents: [
      {
        id: 1,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 2,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 3,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 4,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 5,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 6,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 7,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 8,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 9,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 10,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 11,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 12,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 13,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 14,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 15,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
      {
        id: 16,
        name: "Jason Daloro",
        picture: "/Assets/Seller/ProfilePic.jpg",
        commission: "5%",
        referrals: 23,
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        earnings: 3400,
        joiningDate: "24-03-2021",
      },
    ],
    tickets: [
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 55734432,
        userRole: "seller",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
    ],
    buyers: [
      {
        id: 1,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 2,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 3,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 4,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 5,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 6,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 7,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 8,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 9,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 10,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 11,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 12,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 13,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 14,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
      {
        id: 15,
        name: "Jacob Jason",
        picture: "/Assets/Seller/ProfilePic.jpg",
        amountSpent: 453,
        purchasedProducts: 23,
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        joiningDate: "24-03-2021",
      },
    ],
    sellerApplications: [
      {
        id: 1,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 2,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 3,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 4,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 5,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 6,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 7,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 8,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 9,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 10,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 11,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 12,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 13,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
      {
        id: 14,
        name: "Jhon Mckay",
        logo: "/Assets/Seller/ProfilePic.jpg",
        cover: "/Assets/BecomeASeller/Cover.webp",
        address: "st Paul Street Los Vegas",
        phone: "+923409574",
        email: "JhonMckay@gmail.com",
        personalWebsite: "JhonMckay.com",
        category: "Electronics",
        subCategories: ["Laptops", "Mobiles"],
        shopName: "Shopo Gadgets",
        shopDescription:
          "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        applicationDate: "24-03-2021",
      },
    ],
    tickets: [
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 55734432,
        userRole: "seller",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "buyer",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "closed",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
      {
        ticketId: 1257432,
        userRole: "seller",
        status: "open",
        openDate: "1/4/2022",
        closeDate: "1/5/2022",
      },
    ],
    agentsPayments: [
      {
        id: 1,
        agentId: 1,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 2,
        agentId: 2,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 3,
        agentId: 3,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 4,
        agentId: 4,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 5,
        agentId: 5,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 6,
        agentId: 6,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 7,
        agentId: 7,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 8,
        agentId: 8,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 9,
        agentId: 9,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 10,
        agentId: 10,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 11,
        agentId: 11,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 12,
        agentId: 12,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
    ],
    vendorsPayments: [
      {
        id: 1,
        vendorId: 1,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 2,
        vendorId: 2,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 3,
        vendorId: 3,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 4,
        vendorId: 4,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 5,
        vendorId: 5,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 6,
        vendorId: 6,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 7,
        vendorId: 7,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 8,
        vendorId: 8,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 9,
        vendorId: 9,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 10,
        vendorId: 10,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 11,
        vendorId: 11,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
      {
        id: 12,
        vendorId: 12,
        name: "Shopo Gadgets",
        image: "/Assets/Home/bestproducts/apple-air.webp",
        revenue: 10,
        total: 20,
        btntext: "Release",
      },
    ],
  },
  Home: {
    AllSellersData: [
      {
        id: 1,
        name: "Rayhans",
        rating: 5,
        email: "tofor67338@geekjun.com",
        phoneNumber: "01792166627",
        address: "Dhaka,Bangladesh",
        pic: "/Assets/Home/BestSeller/2.webp",
      },
      {
        id: 2,
        name: "Habbriyi",
        rating: 0,
        email: "rokayo4006@pahed.com",
        phoneNumber: "01792166627",
        address: "Dhaka,Bangladesh",
        pic: "/Assets/Home/BestSeller/shopnoBd.png",
      },
      {
        id: 3,
        name: "Rikayi Rox",
        rating: 3,
        email: "rokayo4006@pahed.com",
        phoneNumber: "01792166627",
        address: "Dhaka,Bangladesh",
        pic: "/Assets/Home/BestSeller/3.webp",
      },
      {
        id: 4,
        name: "Fusion X",
        rating: 4,
        email: "rokayo4006@pahed.com",
        phoneNumber: "01792166627",
        address: "Dhaka,Bangladesh",
        pic: "/Assets/Home/BestSeller/4.webp",
      },
      {
        id: 5,
        name: "Eecoms Shop",
        rating: 1,
        email: "rokayo4006@pahed.com",
        phoneNumber: "01792166627",
        address: "Dhaka,Bangladesh",
        pic: "/Assets/Home/BestSeller/6.webp",
      },
      {
        id: 6,
        name: "Shopno BD",
        rating: 5,
        email: "rokayo4006@pahed.com",
        phoneNumber: "01792166627",
        address: "Dhaka,Bangladesh",
        pic: "/Assets/Home/BestSeller/5.png",
      },
    ],
  },
  AdDetails: {
    images: [
      {
        original: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        thumbnail: "/Assets/Home/bestproducts/apple-watch-pro.webp",
      },
      {
        original: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        thumbnail: "/Assets/Home/bestproducts/apple-watch-pro.webp",
      },
      {
        original: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        thumbnail: "/Assets/Home/bestproducts/apple-watch-pro.webp",
      },
      {
        original: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        thumbnail: "/Assets/Home/bestproducts/apple-watch-pro.webp",
      },
      {
        original: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        thumbnail: "/Assets/Home/bestproducts/apple-watch-pro.webp",
      },
      {
        original: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        thumbnail: "/Assets/Home/bestproducts/apple-watch-pro.webp",
      },
      {
        original: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        thumbnail: "/Assets/Home/bestproducts/apple-watch-pro.webp",
      },
      {
        original: "/Assets/Home/bestproducts/apple-watch-pro.webp",
        thumbnail: "/Assets/Home/bestproducts/apple-watch-pro.webp",
      },
    ],
  },
  PostAD: {
    categories: [
      { name: "Electronics", value: "Electronics" },
      { name: "Arts", value: "Arts" },
      { name: "Fashion", value: "Fashion" },
      { name: "Toys", value: "Toys" },
      { name: "Sports", value: "Sports" },
    ],
    locations: [
      { name: "Nigeria", value: "Nigeria" },
      { name: "USA", value: "USA" },
      { name: "Canada", value: "Canada" },
      { name: "UK", value: "UK" },
    ],
    conditions: [
      { name: "Poor", value: "Poor" },
      { name: "Average", value: "Average" },
      { name: "Good", value: "Good" },
      { name: "New", value: "New" },
    ],
    types: [
      { name: "Items", value: "Items" },
      { name: "Services", value: "Services" },
      { name: "Downloadable", value: "Downloadable" },
    ],
  },
  Advertisements: {
    Ad_Categories: [
      {
        label: "Service",
        name: "service",
        state: "service",
      },
      {
        label: "Downloads",
        name: "downloads",
        state: "downloads",
      },
      {
        label: "Vacancies",
        name: "vacancies",
        state: "vacancies",
      },
    ],
    Locations_Filter: [
      {
        label: "Nigeria",
        name: "nigeria",
        state: "nigeria",
      },
      {
        label: "Canada",
        name: "canada",
        state: "canada",
      },
      {
        label: "USA",
        name: "usa",
        state: "usa",
      },
      {
        label: "UK",
        name: "uk",
        state: "uk",
      },
    ],
    SortBy_Filter: [
      {
        label: "Name",
        name: "name",
        state: "name",
      },
      {
        label: "Price",
        name: "price",
        state: "price",
      },
    ],
  },
};
